### ISSUE TITLE
Fix TQDM error during ingestion

### ISSUE THREAD

**Issue by woop** [gojek/feast#285]
Error that was sent to me from a user over slack

TQDM error when running ingestion: 
```
Process Process-3:
Traceback (most recent call last):
  File "/Users/zhiling/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/zhiling/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zhiling/Documents/work/dev/feast/sdk/python/feast/feature_set.py", line 465, in _listener
    for _ in iter(q.get, None):
  File "/Users/zhiling/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/Users/zhiling/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
OSError: [Errno 9] Bad file descriptor
```

**Comment by woop** [comment]
Fixed by #307
