### ISSUE TITLE
Runtime Dependency Error After Upgrade to Beam 2.9.0

### ISSUE THREAD

**Issue by pradithya** [gojek/feast#44]
During job submission following error is thrown
```
java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setWriteTimeout(I)Lcom/google/api/client/http/HttpRequest;
        at org.apache.beam.sdk.util.RetryHttpRequestInitializer.initialize(RetryHttpRequestInitializer.java:227)
        at com.google.cloud.hadoop.util.ChainingHttpRequestInitializer.initialize(ChainingHttpRequestInitializer.java:52)
        at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:93)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:381)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)
        at com.google.cloud.hadoop.util.ResilientOperation$AbstractGoogleClientRequestExecutor.call(ResilientOperation.java:163)
        at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:64)
```

This is due to dependency to `com.google.http-client` was not updated accordingly

**Comment by pradithya** [comment]
I am making PR for this
